import Sidebar from '@/components/Sidebar'
import Layout from '@/layouts/Layout'
import Head from 'next/head'
import React from 'react'

const index = () => {  
  return (
		<Layout>
			<>
				<Head>
					<title>Create Next App</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<div className='hidden flex-col w-full h-full p-10 lg:flex'>
					<div className='flex justify-center'>
						<h1>Despachos y recogidas</h1>
					</div>
					<div className='flex justify-between'>
						<div>filtros</div>
						<div>acciones</div>
					</div>
					<div className='debug h-full w-full'>tabla</div>
					<div>paginacion</div>
				</div>
				{/* Mobile */}
				<div className='flex flex-col h-full w-full p-3 lg:hidden'>
					<h1>Recogidas y despachos</h1>
					<div className='flex justify-end'>
						<div>filtros</div>
						<div>acciones</div>
					</div>

					<div className='h-full grid grid-cols-2'>
						<div>card lote 1</div>
						<div>card lote 2</div>
						<div>card lote 3</div>
						<div>card lote 4</div>
						<div>card lote 5</div>
						<div>card lote 6</div>
						<div>card lote 7</div>
						<div>card lote 8</div>
						<div>card lote 9</div>
						<div>card lote 10</div>
					</div>


				</div>
			</>
		</Layout>
  )
}

export default index