import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
import React from 'react'

const index = () => {  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='flex h-screen w-screen'>
		<Sidebar />
        <section className='debug w-full h-full'>
          <div className='flex flex-col w-full h-full p-10'>
            <div className='flex justify-between'>
              <div>filtros</div>
              <div>acciones</div>
            </div>
            <div className='debug h-full w-full'>tabla</div>
            <div>paginacion</div>
          </div>
        </section>
      </section>
    </>
  )
}

export default index